name: Copy and Install Node Modules from S3
description: Copies a node_modules tar file from S3, unzips it, and installs dependencies
inputs:
  s3_bucket:
    description: 'S3 bucket path for node_modules tar file'
    required: true
  s3_dir:
    description: 'S3 directory path where tar file is stored'
    required: true
runs:
  using: "composite"
  steps:
    - name: Copy node_modules tar file from S3
      run: |
        sudo su -c "cp ${{ inputs.s3_bucket }}/$${{ inputs.s3_dir }}/node_modules.tar.gz ../../../temp/" ec2-user
    - name: Copy node_modules tar file to working directory
      run: cp ../../../temp/node_modules.tar.gz ./
    - name: Unzip node_modules tar file
      run: tar -xvzf node_modules.tar.gz
    - name: Install dependencies
      if: ${{ hashFiles('package.json') != '' }}
      run: npm install
